name: rullup-ts-num

on:
  push:
    tags: 
      - '*'           # Push events to every tag not containing /
  pull_request:
    branches:
      - main
  # 或者手动触发
  workflow_dispatch:       # 设置手动触发，参考文档 https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2   # 将我们提交的代码 checkout (拷贝) 一份出来
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/setup-node@v1  # 会建立 node 环境，便于我们执行 node 脚本
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: check code   # 检查代码
        run: |
          npm install
          npm run lint
          npm run test

      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: publish                          # 发布 npm 包
        if: ${{contains(github.ref, 'refs/tags/')}}  # 如果有新 tag
        run: |
          npm run build
          npm run build:types
          npm run docs:build
          npm publish --access public
      #- name: deploy                          # 发布文档
      #  if: ${{contains(github.ref, 'refs/tags/')}}
      #  uses: JamesIves/github-pages-deploy-action@4.1.1
      #  with:
      #    branch: main # The branch the action should deploy to.
      #    folder: docs/.vuepress/dist # The folder the action should deploy.

      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0 # This step installs the ssh client into the workflow run. There's many options available for this on the action marketplace.
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Build and Deploy Repo
        uses: JamesIves/github-pages-deploy-action@releases/v3-test
        with:
          branch: main
          # BASE_BRANCH: mian
          # BRANCH: docs-pages
          folder: docs/.vuepress/dist
          ssh: true # SSH must be set to true so the deploy action knows which protocol to deploy with.
          # ssh-keygen -t rsa -b 4096 -C "$(git config user.email)" -f docs-pages -N ""
          # https://wenlong201807.github.io/rollup-git-ts-md
          # 建站说明 https://docs.github.com/en/pages

# 参考学习 https://zhuanlan.zhihu.com/p/258895977  
